### PR TITLE
Fix pagination for various response types

### LINKED ISSUE #135: Weird behavior with .limit on actions api endpoints
I've run into some weird behavior when trying to set a limit for results coming from the actions api (it may affect other areas - I haven't tested beyond these endpoints). Seems to be a problem with the paging, but I haven't dug into the underlying code.

```
ok = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh"
)

error = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh",
  .limit = 1
)

badly_formed = gh::gh(
  "GET /repos/:owner/:repo/actions/runs",
  owner = "r-lib",
  repo = "gh",
  .limit = 10
)
```

### PR DESCRIPTION
**Pull request by gaborcsardi**
Use 'total_count' and info from the schema on
how to calculate the "length" of a response.

Fixes #135.

### CODE REVIEW

File: R/gh.R [hunk 1]
```diff
@@ -195,11 +196,13 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
...
+    len <- len + gh_response_length(res2)
+
     attributes(res3) <- attributes(res2)
     res <- res3
   }
 
-  if (! is.null(.limit) && length(res) > .limit) {
+  if (! is.null(.limit) && len > .limit) {
     res_attr <- attributes(res)
     res <- res[seq_len(.limit)]
```
Comment (rundel) [inline R/gh.R:207]: There needs to be alternative behavior here since for the object case we need to subset the array within the object

File: R/gh.R [hunk 2]
```diff
@@ -208,6 +211,24 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
...
+    # and take the first list element to get the length
+    lst <- vapply(res, is.list, logical(1))
+    nm <- setdiff(
+      names(res),
+      c("total_count", "incomplete_results", "repository_selection")
+    )
+    tgt <- which(lst[nm])[1]
+    if (is.na(tgt)) length(res) else length(res[[ nm[tgt] ]])
+    length(res[[2]])
+  } else {
```
Comment (rundel) [inline R/gh.R:226]: I think there needs to be a third case here for endpoints like `/user`

File: R/gh.R [hunk 3]
```diff
@@ -208,6 +211,24 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
...
 
+gh_response_length <- function(res) {
+  if (!is.null(names(res)) && length(res) > 1 &&
+      names(res)[1] == "total_count") {
+    # Ignore total_count, incomplete_results, repository_selection
+    # and take the first list element to get the length
+    lst <- vapply(res, is.list, logical(1))
+    nm <- setdiff(
+      names(res),
+      c("total_count", "incomplete_results", "repository_selection")
```
Comment (rundel) [inline R/gh.R:222]: I assume these are coming from the API description?

File: R/gh.R [hunk 4]
```diff
@@ -208,6 +211,24 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
...
+    )
+    tgt <- which(lst[nm])[1]
+    if (is.na(tgt)) length(res) else length(res[[ nm[tgt] ]])
+    length(res[[2]])
```
Comment (rundel) [inline R/gh.R]: Logic above seems a bit wonky? Seems like `length(res[[2]])` or the conditional should be there not both.

File: R/gh.R [hunk 5]
```diff
@@ -208,6 +211,24 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
   res
 }
 
+gh_response_length <- function(res) {
+  if (!is.null(names(res)) && length(res) > 1 &&
+      names(res)[1] == "total_count") {
```
Comment (rundel) [inline R/gh.R:216]: Is `total_count` always the first entry or would it be better to just use `%in%`?

File: R/gh.R [hunk 6]
```diff
@@ -208,6 +211,24 @@ gh <- function(endpoint, ..., per_page = NULL, .token = NULL, .destfile = NULL,
...
+    # Ignore total_count, incomplete_results, repository_selection
+    # and take the first list element to get the length
+    lst <- vapply(res, is.list, logical(1))
+    nm <- setdiff(
+      names(res),
+      c("total_count", "incomplete_results", "repository_selection")
+    )
+    tgt <- which(lst[nm])[1]
```
Comment (rundel) [inline R/gh.R:224]: Include some kind of runtime assert that checks that there is only one target? If not throw an error and ask the user to report the endpoint?

File: R/gh.R (hunk 4 above)
Comment (gaborcsardi) [reply R/gh.R]: This was a typo, removed the `length(res[[2]])` line.

File: R/gh.R (hunk 5 above)
Comment (gaborcsardi) [reply R/gh.R:216]: It seems like it is the first entry, yeah.

File: R/gh.R (hunk 1 above)
Comment (gaborcsardi) [reply R/gh.R:207]: Yeah, but it is not entirely clear how to do that. This branch is only used if we got more items than requested, which might not even happen. So this is not super important I think. I'll protect this with `length(res) == len`, so we only do it in the non-named response case.

Comment (rundel) [reply R/gh.R:207]: I was thinking of a case where someone set `.limit = 101` in which case they would now get 200 results (not the end of the world).

Can we not use the same logic to find the "target" as the unnamed list and subset it?

File: R/gh.R (hunk 2 above)
Comment (gaborcsardi) [reply R/gh.R:226]: The length is only really important if `.limit` is specified, and people will not do that for `/user`. 

We could do more heuristics, but I want to be cautious. So for `/user` we can essentially keep the old behavior, nothing changes imo.

File: R/gh.R (hunk 3 above)
Comment (gaborcsardi) [reply R/gh.R:222]: yeah

File: R/gh.R (hunk 6 above)
Comment (gaborcsardi) [reply R/gh.R:224]: Well, you PR merges all elements, and I looked over the spec, so this should be fine, I think. If there are multiple of them, we'd still want to do something, so I think taking the first is fine.

Comment (rundel) [reply R/gh.R:224]: Makes sense, particularly if we're just looking for the length

File: R/gh.R (hunk 1 above)
Comment (gaborcsardi) [reply R/gh.R:207]: Yeah, OTOH subsetting based on some target list is potentially destructive, while just looking up the length os probably not. 

So I think we could only subset in the non-named case, to keep the old behavior for that. The behavior for the named case is much improved already, so it is fine I think.

File: R/gh.R (hunk 2 above)
Comment (rundel) [reply R/gh.R:226]: This seems reasonable, I will need to check that ghclass is not doing something silly like setting `.limit` for everything

File: R/gh.R (hunk 1 above)
Comment (rundel) [reply R/gh.R:207]: Sounds good - I think the usage of `.limit` is quite rare already and this should cover the vast majority of use cases

**Comment by gaborcsardi** [comment]
@rundel Thanks for looking at this. I think it is definitely an improvement and hopefully we were conservative enough not to break anyone's code.

There is still this to fix:
```r
se = gh::gh(
  "GET /search/code?q=foobar",
  .limit=101
)
lengths(se)
#>        total_count incomplete_results              items
#>                  2                  2                200

se$total_count
#> [1] 18043087 18080930

se$incomplete_results
#> [1]  TRUE FALSE
```

In the future I am hoping that we can use r-lib/webfakes and the info from the spec to write a test suite with reasonable coverage, and then we can be more confident about handling the output of the API better.

**Comment by gaborcsardi** [comment]
Oh, yeah the issue with that code is this line:
```
          if (is.atomic(z)) unique(z)
```
and of course the API provided different values for `total_count` and `incomplete_results` for the two responses. I'll tweak that a bit and will use the latest value for these two fields.
